spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Netflix Ribbon 대신 Spring Cloud LoadBalancer 사용

feign:
  client:
    config:
      default: #모든 클라이언트에 적용되는 공통 설정
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full #
      user-service:


management:
  endpoints:
    web:
      exposure: refresh